// src/components/Environment.svelte
<script>
  import { location } from '../store.js'
  import Title from './Title.svelte'
  import Resources from './Resources.svelte'
  import Table from './Table.svelte'
  import Map from './Map.svelte'
  import RecordHighlight from './RecordHighlight.svelte'
  import jsonToURL from '../js/jsonToURL.js'
  
  // Soil table
  const columns = ["Soil Type", "Group", "Description"]
  const alignRight = []
  let rows = []

  // check stuff
  let floodplainReport = {
    top: '',
    detail: '',
    headline: ''
  }
  let waterQualityReport = JSON.parse(JSON.stringify(floodplainReport))
  let watershedReport = JSON.parse(JSON.stringify(floodplainReport))
  let districtReport = JSON.parse(JSON.stringify(floodplainReport))

  // Map
  let showMap = false

  // Resources
  const resourceLinks = [
    {
      name: 'What is a "floodplain"?',
      url: 'https://en.wikipedia.org/wiki/Floodplain'
    },
    {
      name: 'What is a "watershed"?',
      url: 'https://en.wikipedia.org/wiki/Watershed'
    },
    {
      name: 'Storm Water Services',
      url: 'https://charlottenc.gov/stormwater/Pages/default.aspx'
    },
    {
      name: 'Floodplain data on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=flood'
    },
    {
      name: 'Watershed data on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=watershed'
    },
    {
      name: 'Storm Water data on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=storm'
    }
  ]

  // Total impervious surface
  let imperviousTotal = 0

  location.subscribe(value => {
		fetchData()
  })

  function fetchData() {
    // reset catchers
    [floodplainReport, waterQualityReport, watershedReport, districtReport].forEach(item => {
      item = {
        top: '',
        detail: '',
        headline: ''
      }
    })
    rows = []

    soils($location.groundpid)
    floodplain($location.groundpid)
    waterqualitybuffer($location.groundpid)
    district($location.groundpid)
    watershed($location.lnglat[0], $location.lnglat[1])
  }

  //***************************************************************
  // district
  //***************************************************************
  function watershed(lng, lat) {
    const params = {
      columns: "name,type,subarea",
      geom_column: "the_geom",
      limit: 1
    }

    fetch(`https://api.mcmap.org/v1/intersect_point/watersheds/${lng},${lat},4326?${jsonToURL(params)}`)
      .then(response => response.json())
      .then(data => {
        if (data.length > 0) {
          const warning = data[0].type.length > 1 ?
            `This is a <a href="http://charlottenc.gov/StormWater/Regulations/Documents/WatershedRulesSummary.pdf" target="_blank"  rel="noopener">${data[0].type} watershed (${data[0].subarea})</a>.<br>`
            : ''
          watershedReport = {
            top: 'This property is in the',
            detail: warning + 'A watershed, or drainage basin, is an area of land where all surface water converges to a single point at a lower elevation, usually the exit of the basin such as a river, lake, or wetland.',
            headline: data[0].name.toUpperCase() + ' WATERSHED'
          }
        }
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })
  }

  //***************************************************************
  // district
  //***************************************************************
  function district(pid) {
    const params = {
      columns: "type, name",
      filter: `tax_parcels.pid = '${
        pid
      }' and post_construction_layers.type in ('TRANSIT CORRIDOR', 'BUSINESS CORRIDOR') `,
      geom_column_from: "the_geom",
      geom_column_to: "the_geom"
    }

    fetch(`https://api.mcmap.org/v1/intersect_feature/tax_parcels/post_construction_layers?${jsonToURL(params)}`)
      .then(response => response.json())
      .then(data => {
        if (data.length > 0) {
          districtReport = {
            top: 'This property is in a',
            detail: 'PCCO mitigation options apply. For more information, please call <a href="tel:+7044325571">704.432.5571</a>.',
            headline: 'DISTRESSED BUSINESS DISTRICT'
          }
        } else {
          districtReport = {
            top: 'This property is not in a distressed business district.',
            detail: null,
            headline: null
          }
        }
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })
  }

  //***************************************************************
  // water quality buffer
  //***************************************************************
  function waterqualitybuffer(pid) {
    const params = {
      columns: "distinct type, label",
      filter: `tax_parcels.pid = '${pid}'`,
      geom_column_from: "the_geom",
      geom_column_to: "the_geom"
    }

    fetch(`https://api.mcmap.org/v1/intersect_feature/tax_parcels/water_quality_buffers?${jsonToURL(params)}`)
      .then(response => response.json())
      .then(data => {
        if (data.length > 0) {
          waterQualityReport = {
            top: 'This property is in a',
            detail: `The buffer(s) are: <strong>${data.map(el => el.label + ' ' + el.type).join(', ')}</strong>. Special restrictions may apply. For more information, please call <a href="tel:+9807214191">980.721.4191</a> for existing single-family lots and those projects not needing a grading permit or <a href="tel:+7044325570">704.432.5570</a> for other projects.`,
            headline: 'WATER QUALITY BUFFER'
          }
        } else {
          waterQualityReport = {
            top: 'This property is not in a water quality buffer.',
            detail: null,
            headline: null
          }
        }
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })
  }

  //***************************************************************
  // Floodplain
  //***************************************************************
  function floodplain(pid) {
    const params = {
      columns: "view_regulated_floodplains.gid",
      filter: `tax_parcels.pid = '${pid}'`,
      geom_column_from: "the_geom",
      geom_column_to: "the_geom"
    }

    fetch(`https://api.mcmap.org/v1/intersect_feature/tax_parcels/view_regulated_floodplains?${jsonToURL(params)}`)
      .then(response => response.json())
      .then(data => {
        if (data.length > 0) {
          floodplainReport = {
            top: 'This property is in a',
            detail: 'Special restrictions may apply. For more information, please call <a href="tel:7043363728">704.336.3728</a>.',
            headline: 'REGULATED FLOODPLAIN'
          }
        } else {
          floodplainReport = {
            top: 'This property is not in a regulated floodplain.',
            detail: null,
            headline: null
          }
        }
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })
  }

  //***************************************************************
  // Soils
  //***************************************************************
  function soils(pid) {
    rows = []

    const params = {
      columns: "distinct name,description,hydrologic_group",
      filter: `tax_parcels.pid = '${pid}'`,
      geom_column_from: "the_geom",
      geom_column_to: "the_geom"
    }

    fetch(`https://api.mcmap.org/v1/intersect_feature/tax_parcels/soil?${jsonToURL(params)}`)
      .then(response => response.json())
      .then(data => {
        // make records for table
        data.forEach(el => {
          rows.push([
            el.name,
            el.description,
            el.hydrologic_group
          ])
        })
      })
      .then(() => {
        rows = rows
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })
  }

</script>

<Title title="Environment" icon="environment" />

<Map showMap={showMap} toggleLayers="environment"  />

<div class="flex flex-row flex-wrap justify-around print:block">
  <RecordHighlight {...floodplainReport} />
  <RecordHighlight {...waterQualityReport} />
  <RecordHighlight {...districtReport} />
  <RecordHighlight {...watershedReport} />
</div>

<Table caption="Soil Types" rows={rows} columns={columns} alignRight={alignRight} />

<Resources links={resourceLinks} />

// app/js/components/environment.vue
<template lang="html">
    <div>
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div v-if="resultsFloodplain">
                    <div class="report-record-highlight">
                        <svg class="icon icon-floodplain"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-floodplain"></use></svg>
                        <h2 v-if="resultsFloodplain.length > 0">This property is in a</h2>
                        <h2 v-else>This property is not in a regulated floodplain.</h2>
                        <h1 v-if="resultsFloodplain.length > 0">REGULATED FLOODPLAIN</h1>
                        <h4 v-if="resultsFloodplain.length > 0"><a target="_blank"  rel="noopener" href={fz}>Special restrictions may apply</a>. For more information, please call 704.336.3728.</h4>
                    </div>
                </div>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div v-if="resultsWaterquality">
                    <div class="report-record-highlight">                        
                        <svg class="icon icon-water-quality"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-water-quality"></use></svg>
                        <div v-if="resultsWaterquality.length > 0">
                            <h2>This property is in a</h2>
                            <h1>WATER QUALITY BUFFER</h1>
                            <h4>The buffer(s) are: <strong>{{ resultsWaterquality | waterquality }}</strong>. <a href="http://charmeck.org/stormwater/regulations/Pages/Post-ConstructionStormWaterOrdinances.aspx" target="_blank"  rel="noopener">Special restrictions may apply</a>.
                                For more information, please call 980.721.4191 for existing single-family lots and those projects not needing a grading permit or call 704.432.5570 for other projects.</h4>
                        </div>
                        <div v-else>
                            <h2>
                                This property is not in a Water Quality Buffer.</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div v-if="resultsPostconstruction">
                    <div class="report-record-highlight">
                        <svg class="icon icon-construction"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-construction"></use></svg>
                        <div v-if="resultsPostconstruction.length > 0">
                            <h2>This property is in a</h2>
                            <h1>{{ resultsPostconstruction | postconstruction }}</h1>
                            <h4><a href="http://charmeck.org/stormwater/regulations/Pages/Post-ConstructionStormWaterOrdinances.aspx" target="_blank"  rel="noopener">PCCO mitigation options apply</a>. For more information, please call 704.432.5571.</h4>
                        </div>
                        <div v-else>
                            <h2>
                                This property is not in a Distressed Business District or Transit Station Area.</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsWatershed">
                    <svg class="icon icon-environment"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-environment"></use></svg>
                    <h2>This property is in the</h2>
                    <h1>{{resultsWatershed[0].name.toUpperCase()}} WATERSHED</h1>
                    <h4>
                        <span style="font-weight: bold;" v-if="resultsWatershed[0].type.length > 1">This is a <a href="http://charlottenc.gov/StormWater/Regulations/Documents/WatershedRulesSummary.pdf" target="_blank"  rel="noopener">{{resultsWatershed[0].type}} watershed ({{resultsWatershed[0].subarea}})</a>.<br></span>
                        A watershed, or drainage basin, is an area of land where all surface water converges to a single point at a lower elevation, usually the exit of the basin such as a river, lake, or wetland.
                    </h4>
                </div>
            </div>
        </div>
        <div class="mdl-typography--text-center">
            <div v-if="resultsSoil">
                <table class="mdl-data-table mdl-js-data-table">
                    <caption>Soil Types</caption>
                    <thead>
                        <tr>
                            <th class="mdl-data-table__cell--non-numeric">Type</th>
                            <th class="mdl-data-table__cell--non-numeric">Group</th>
                            <th class="mdl-data-table__cell--non-numeric">Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(item, index) in resultsSoil">
                            <td class="mdl-data-table__cell--non-numeric">
                                {{item.name}}
                            </td>
                            <td class="mdl-data-table__cell--non-numeric">
                                {{item.hydrologic_group}}
                            </td>
                            <td class="mdl-data-table__cell--non-numeric">
                                {{item.description}}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="report-moreinfo mdl-typography--text-left">
            <h5>For more information, please visit:</h5>
            <ul class="list-unstyled">
                <li><a href="http://charmeck.org/stormwater/Pages/default.aspx" target="_blank"  rel="noopener">Storm Water Services</a></li>
                <li><a href="http://charmeck.org/mecklenburg/county/LUESA/WaterandLandResources/Pages/default.aspx" target="_blank"  rel="noopener">Water &amp; Land Resources</a></li>
                <li><a href="http://charmeck.org/mecklenburg/county/HealthDepartment/EnvironmentalHealth/GWS/Pages/default.aspx" target="_blank"  rel="noopener">Groundwater &amp; Wastewater Services</a></li>
                <li><a href="https://mecklenburgcounty.exavault.com/p/waterquality%252FWQ%2520Buffers/WaterQualityBufferImplementationGuidelines.pdf" target="_blank"  rel="noopener">Water Quality Buffer Implementation Guidelines</a></li>
            </ul>
        </div>
    </div>
</template>

<script>
    import jsonToURL from '../modules/jsontourl';
    export default {
        name: 'environment',
        data: function() {
            return {
                resultsFloodplain: null,
                resultsSoil: null,
                resultsWaterquality: null,
                resultsPostconstruction: null,
                resultsWatershed: null
            }
        },
        watch: {
            '$parent.sharedState.selected.lnglat': 'getResults',
            '$parent.sharedState.show': 'getResults'
        },
        filters: {
            postconstruction: function(items) {
                items = items.filter(function(item) {
                    return item.type === 'TRANSIT CORRIDOR' || item.type === 'BUSINESS CORRIDOR';
                });
                items = items.map(function(item) {
                    return item.type;
                });
                items = items.join(' and ');
                items = items.replace('BUSINESS CORRIDOR', 'Distressed Business District'.toUpperCase()).replace('TRANSIT CORRIDOR', 'Transit Station Area'.toUpperCase());
                return items;
            },
            waterquality: function(items) {
                let typesArr = [];
                for (let i = 0; i < items.length; i++) {
                    typesArr.push(`${items[i].label} ${items[i].type}`);
                }
                return typesArr.join(', ');
            }
        },
        mounted: function() {
            this.getResults();
        },
        methods: {
            apiFetch: function(params, url, setter) {
                let _this = this;
                return fetch(`${url}?${jsonToURL(params)}`)
                    .then(function(response) {
                        return response.json();
                    }).then(function(data) {
                        _this[setter] = data;
                    }).catch(function(ex) {
                        console.log('parsing failed', ex);
                    });
            },
            getResults: function() {
                let _this = this;
                if (_this.$parent.sharedState.selected.lnglat && _this.$parent.sharedState.show.indexOf('environment') !== -1) {
                    // floodplain
                    _this.apiFetch({
                            'columns': 't.gid',
                            'filter': `f.pid = '${_this.$parent.sharedState.selected.pid}'`,
                            'geom_column_from': 'the_geom',
                            'geom_column_to': 'the_geom'
                        },
                        'https://mcmap.org/api/intersect_feature/v1/tax_parcels/view_regulated_floodplains',
                        'resultsFloodplain'
                    );
                    // post construction
                    _this.apiFetch({
                            'columns': 'type, name',
                            'filter': `f.pid = '${_this.$parent.sharedState.selected.pid}' and t.type in ('TRANSIT CORRIDOR', 'BUSINESS CORRIDOR') `,
                            'geom_column_from': 'the_geom',
                            'geom_column_to': 'the_geom'
                        },
                        'https://mcmap.org/api/intersect_feature/v1/tax_parcels/post_construction_layers',
                        'resultsPostconstruction'
                    );
                    // soil
                    _this.apiFetch({
                            'columns': 'distinct name,description,hydrologic_group',
                            'filter': `f.pid = '${_this.$parent.sharedState.selected.pid}'`,
                            'geom_column_from': 'the_geom',
                            'geom_column_to': 'the_geom'
                        },
                        'https://mcmap.org/api/intersect_feature/v1/tax_parcels/soil',
                        'resultsSoil'
                    );
                    // water quality buffers
                    _this.apiFetch({
                            'columns': 'distinct type,label',
                            'filter': `f.pid = '${_this.$parent.sharedState.selected.pid}'`,
                            'geom_column_from': 'the_geom',
                            'geom_column_to': 'the_geom'
                        },
                        'https://mcmap.org/api/intersect_feature/v1/tax_parcels/water_quality_buffers',
                        'resultsWaterquality'
                    );
                    // watersheds
                    _this.apiFetch({
                            'columns': 'name,type,subarea',
                            'geom_column': 'the_geom'
                        },
                        `https://mcmap.org/api/intersect_point/v1/watersheds/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsWatershed'
                    );
                }
            }
        }
    }
</script>

<style lang="css">

</style>
