// src/components/Impervious.svelte
<script>
  import { location } from '../store.js'
  import Title from './Title.svelte'
  import Resources from './Resources.svelte'
  import Table from './Table.svelte'
  import Map from './Map.svelte'
  import RecordHighlight from './RecordHighlight.svelte'
  import jsonToURL from '../js/jsonToURL.js'
  import { formatCommas } from '../js/formatNumbers.js'

  // Base table
  const columns = ["Category", "Surface Type", "Area"]
  const alignRight = [3]
  let rows = []

  // Map
  let showMap = false

  // Resources
  const resourceLinks = [
    {
      name: 'What is "impervious surface"?',
      url: 'https://en.wikipedia.org/wiki/Impervious_surface'
    },
    {
      name: 'Charlotte-Mecklenburg Storm Water Services',
      url: 'https://charlottenc.gov/stormwater/Pages/default.aspx'
    },
    {
      name: 'Impervious Surface data on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=impervious'
    }
  ]

  // Total impervious surface
  let imperviousTotal = 0

  location.subscribe(value => {
		fetchData()
	})

  function fetchData() {
    // reset variables
    rows = []
    imperviousTotal = 0

    const params = {
      columns: "sum(sum_of_area) as area, subtheme, category",
      filter: `commonpid='${$location.pid}'`,
      sort: "subtheme",
      group: "subtheme, category"
    }

    fetch(`https://api.mcmap.org/v1/query/impervious_surface_area?${jsonToURL(params)}`)
      .then(response => response.json())
      .then(data => {
        // make records for table
        data.forEach(el => {
          rows.push([
            el.category.charAt(0).toUpperCase() + el.category.slice(1),
            el.subtheme,
            `${formatCommas(el.area)} Sq. Ft.`
          ])
          // set impervious total
          imperviousTotal += el.area
        })
      })
      .then(() => {
        rows = rows
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })
  }

</script>

<Title title="IMPERVIOUS SURFACE" icon="impervious" />

<Map showMap={showMap} toggleLayers="impervious"  />

<div class="flex flex-row flex-wrap justify-around">
  <RecordHighlight top="You have" sub="of Impervious Surface" headline={formatCommas(imperviousTotal) + ' Sq. Ft.'} />
</div>

<Table rows={rows} columns={columns} alignRight={alignRight} />

<Resources links={resourceLinks} />

// app/js/components/impervious.vue
<template lang="html">
    <div>
        <div class="mdl-typography--text-center">
            <div class="report-record-highlight">
                <i class="icon icon-impervious"></i>
                <h2>You have</h2>
                <h1 v-if="results">{{ total() | area }}</h1>
                <h3>of Impervious Surface</h3>
                <h4></h4>
            </div>
            <table v-if="results" class="mdl-data-table mdl-js-data-table" style="min-width: 300px; max-width: 100%;">
                <caption>Details</caption>
                <thead>
                    <tr>
                        <th class="mdl-data-table__cell--non-numeric">Type</th>
                        <th>Area</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in results">
                        <td class="mdl-data-table__cell--non-numeric">
                            {{item.subtheme}}
                        </td>
                        <td class="nowrap">
                            {{ item.area | area }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="report-moreinfo mdl-typography--text-left">
            <p>Impervious surfaces are mainly artificial structures, such as pavements (roads, sidewalks, driveways and parking lots) and rooftops that are covered by impenetrable materials such as asphalt, concrete, brick, wood and stone.</p>
            <h5>For more information, please visit:</h5>
            <ul class="list-unstyled">
                <li><a href="http://charmeck.org/stormwater/FeesandBilling/Pages/Default.aspx" target="_blank"  rel="noopener">Charlotte-Mecklenburg Storm Water Services</a></li>
            </ul>
        </div>
    </div>
</template>

<script>
    import jsonToURL from '../modules/jsontourl';
    import format from 'format-number';
    export default {
        name: 'impervious',
        data: function() {
            return {
                results: null
            }
        },
        filters: {
            area: function(num) {
                return format({
                    'truncate': 0,
                    'suffix': ' Sq. Ft.'
                })(num);
            }
        },
        watch: {
            '$parent.sharedState.selected.lnglat': 'getResults',
            '$parent.sharedState.show': 'getResults'
        },
        mounted: function() {
            this.getResults();
        },
        methods: {
            getResults: function() {
                let _this = this;
                if (_this.$parent.sharedState.selected.lnglat && _this.$parent.sharedState.show.indexOf('impervious') !== -1) {
                    let params = {
                        'columns': 'sum(sum_of_area) as area, subtheme',
                        'filter': `commonpid='${_this.$parent.sharedState.selected.pid}'`,
                        'sort': 'subtheme',
                        'group': 'subtheme'
                    };
                    fetch(`https://mcmap.org/api/query/v1/impervious_surface_area?${jsonToURL(params)}`)
                        .then(function(response) {
                            return response.json();
                        }).then(function(data) {
                            _this.results = data;
                        }).catch(function(ex) {
                            console.log('parsing failed', ex);
                        });
                }
            },
            total: function() {
                let total = 0;
                this.results.forEach(function(item) {
                    total = total + Number(item.area);
                });
                return total;
            }
        }
    }
</script>

<style lang="css">

</style>
