// src/components/Schools.svelte
<script>
  import { location } from '../store.js'
  import Title from './Title.svelte'
  import Resources from './Resources.svelte'
  import Table from './Table.svelte'
  import Map from './Map.svelte'
  import jsonToURL from '../js/jsonToURL.js'
  import { formatCommas } from '../js/formatNumbers.js'

  // Magnet table
  const magnetTable = {
    columns: ["School", "Focus", "Grades", "Address", "Distance"],
    alignRight: [5],
    rows: []
  }

  // Current schools table
  const schoolsCurrent = {
    columns: ["School", "Grades", "Address", "Distance"],
    alignRight: [4],
    rows: []
  }

  // Future schools table
  const schoolsFuture = JSON.parse(JSON.stringify(schoolsCurrent))

  // Magnet Zone
  let zone = ''

  // Map
  let showMap = false
  let mapPoints = []

  // Resources
  const resourceLinks = [
    {
      name: 'Charlotte-Mecklenburg Schools',
      url: 'http://www.cms.k12.nc.us/'
    },
    {
      name: 'School data on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=school'
    }
  ]

  location.subscribe(value => {
		fetchData()
	})

  function fetchData() {
    // reset catchers
    [magnetTable, schoolsCurrent, schoolsFuture].forEach(item => {
      item.rows = []
    })
    zone = ''
    mapPoints = []

    fetchMagnet($location.lnglat[0], $location.lnglat[1])
    fetchSchools($location.lnglat[0], $location.lnglat[1])
  }

  function fetchSchools(lng, lat) {
    const urls = [
      `https://api.mcmap.org/v1/nearest/cms_parcels/${lng},${lat},4326?columns=high_zone,gradek,grade1,grade2,grade3,grade4,grade5,grade6,grade7,grade8,grade9,grade10,grade11,grade12&limit=1`,
      `https://api.mcmap.org/v1/nearest/cms_parcels_future_py/${lng},${lat},4326?columns=high_zone,gradek,grade1,grade2,grade3,grade4,grade5,grade6,grade7,grade8,grade9,grade10,grade11,grade12&limit=1`
    ]

    Promise.all(urls.map(url =>
      fetch(url).then(resp => resp.json())
    )).then(jsons => {

      // set transportation zone
      zone = jsons[0][0]["high_zone"];

      jsons.forEach(elem => {
        delete elem[0].distance
        delete elem[0].high_zone
      })

      // school numbers to fetch
      const schlnums = [...new Set(Object.values(jsons[0][0]).concat(Object.values(jsons[1][0])))]

      fetch(`https://api.mcmap.org/v1/query/cms_schools?columns=city,num as schlnum,address,name,type,ST_Distance(geom,ST_Transform(GeomFromText('POINT( ${lng} ${lat} )',4326), 2264)) as distance,st_x(st_transform(geom, 4326)) as lng, st_y(st_transform(geom, 4326)) as lat&filter=num in(${schlnums.join()})`)
        .then(schools => schools.json())
        .then(schools => {

          schools.forEach(school => {
            mapPoints.push({
              label: school.type.charAt(0),
              lngLat: [school.lng, school.lat],
              name: school.name,
              address: `${school.address}, ${school.city}`
            })
          })

          jsons.forEach((elem, idx) => {
            let results = []
            let schls = [...new Set(Object.values(elem[0]))]

            schls.forEach(scl => {
              let grades = []

              Object.keys(elem[0]).forEach(key => {
                if (elem[0][key] === scl) grades.push(key.replace("grade", '').toUpperCase())
              })

              let result = JSON.parse(JSON.stringify(schools.filter(el => el.schlnum === scl)[0]))
              result.grades = grades

              results.push([
                result.name,
                result.grades.join(', '),
                result.address,
                `${formatCommas(result.distance / 5280, 1)} miles`
              ])
            })

            idx === 0 ? schoolsCurrent.rows = results : schoolsFuture.rows = results
          })

        })

    })
  }

  function fetchMagnet(lng, lat) {
    const params = {
      filter: "magnet in ('Full', 'Partial')",
      columns: `num,city,address,name,grade_level,mag_focus,st_x(st_transform(geom, 4326)) as lng,
          st_y(st_transform(geom, 4326)) as lat,magnet,
          ST_Distance(geom,ST_Transform(
          GeomFromText('POINT( ${lng} ${lat} )',4326), 2264)) as distance`,
      sort: 'distance'
    }

    fetch(`https://api.mcmap.org/v1/query/cms_schools?${jsonToURL(params)}`)
      .then(response => response.json())
      .then(data => {
        // make records for table
        data.forEach(el => {
          magnetTable.rows.push([
            el.name,
            el.mag_focus,
            el.grade_level,
            `${el.address}, ${el.city}`,
            `${formatCommas(el.distance / 5280, 1)} miles`
//                [4429, 8364, 5532, 8482, 7405, 7496, 5520].indexOf(Number(el.num)) !== -1 ? 'All' : '',
          ])
        })
      })
      .then(() => {
        magnetTable.rows = magnetTable.rows
        mapPoints = mapPoints
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })
  }

</script>


<Title title="SCHOOLS" icon="school" />

<Map showMap={showMap} mapPoints={mapPoints} />

<Table rows={schoolsCurrent.rows} columns={schoolsCurrent.columns} caption="Current School Year" alignRight={schoolsCurrent.alignRight} />

<Table rows={schoolsFuture.rows} columns={schoolsFuture.columns} caption="Next School Year" alignRight={schoolsFuture.alignRight} />

<Table rows={magnetTable.rows} columns={magnetTable.columns} caption={'Magnet Schools (You Are in <a href="https://cmschoice.org/your-choices/transportation-zones/" target="_blank">Zone ' + zone + '</a>)'} alignRight={magnetTable.alignRight} />

<p class="pt-8 pb-2">
  Transportation eligibility is determined by the transportation zone in which you live.
  The county is divided into three transportation zones:
  violet, blue and green.
  Magnet schools are assigned a zone to serve with transportation. Some programs
  provide county-wide transportation, meaning that regardless of your zone,
  you would receive transportation. For more information please contact
  Charlotte-Mecklenburg School Transportation Services at <a href="tel:9803436715">(980) 343-6715</a>.
</p>

<p class="pt-2 pb-8">
  School assignment information is based on data provided by Charlotte-Mecklenburg Schools and Mecklenburg
  County GIS. For questions, concerns, or confirmation of schools assignments, please contact Charlotte-Mecklenburg Schools at <a href="email:planning@cms.k12.nc.us">planning@cms.k12.nc.us</a> or <a href="tel:9803436246">(980) 343-6246</a>.
</p>

<Resources links={resourceLinks} />

// app/js/components/schools.vue
<template lang="html">
    <div>
        <div class="mdl-typography--text-center">
            <div class="report-record-highlight" v-if="resultsElementary.length > 0">
                <i class="icon icon-school"></i>
                <h2>Your ELEMENTARY school is</h2>
                <h1>{{resultsElementary[0].name.toUpperCase()}}</h1>
                <h3><a href="javascript:void(0)" v-on:click="locationClick(resultsElementary[0])">
                        {{resultsElementary[0].address}}</a></h3>
                <h4>{{ resultsElementary[0].dist | distance }}</h4>
            </div>
        </div>
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsMiddle.length > 0">
                    <i class="icon icon-school"></i>
                    <h2>Your MIDDLE school is</h2>
                    <h1>{{resultsMiddle[0].name.toUpperCase()}}</h1>
                    <h3><a href="javascript:void(0)" v-on:click="locationClick(resultsMiddle[0])">
                            {{resultsMiddle[0].address}}</a></h3>
                    <h4>{{ resultsMiddle[0].dist | distance }}</h4>
                </div>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsHigh.length > 0">
                    <i class="icon icon-school"></i>
                    <h2>Your HIGH school is</h2>
                    <h1>{{resultsHigh[0].name.toUpperCase()}}</h1>
                    <h3><a href="javascript:void(0)" v-on:click="locationClick(resultsHigh[0])">
                            {{resultsHigh[0].address}}</a></h3>
                    <h4>{{ resultsHigh[0].dist | distance }}</h4>
                </div>
            </div>
        </div>
        <div class="mdl-typography--text-center">
            <div class="report-record-highlight" v-if="resultsHigh.length > 0">
                <i class="icon icon-bus"></i>
                <h2>Your Transportation Zone is</h2>
                <h1>{{resultsHigh[0].zone.toUpperCase()}}</h1>
                <p v-if="tmpTransportationZone && resultsHigh[0].zone.toUpperCase() !== tmpTransportationZone[0].choicezn.toUpperCase()">
                    For the 2017-2018 school year, your <strong>Transportation Zone</strong> will change to <strong>{{ tmpTransportationZone[0].choicezn.toUpperCase() }}</strong>.
                </p>
            </div>
        </div>
        <div v-if="resultsMagnet">
            <table class="mdl-data-table mdl-js-data-table">
                <caption>Magnet Schools</caption>
                <thead>
                    <tr>
                        <th class="mdl-data-table__cell--non-numeric">School</th>
                        <th class="mdl-data-table__cell--non-numeric">Address</th>
                        <th class="col-responsive">Distance</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in resultsMagnet">
                        <td class="mdl-data-table__cell--non-numeric">
                            {{item.schlname}}{{ item.schl | getAsterik }}
                        </td>
                        <td class="mdl-data-table__cell--non-numeric">
                            <a href="javascript:void(0)" v-on:click="locationClick(index)">
                                    {{item.address}}, {{item.city}}</a>
                        </td>
                        <td class="nowrap col-responsive">
                            {{ item.distance | distance }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="report-moreinfo mdl-typography--text-left">
            <p>
                Transportation eligibility is determined by the transportation zone in which you live. The county is divided into four transportation zones: violet, grey, blue, and green. Magnet schools are assigned a zone to serve with transportation. If the distance
                is to the magnet greater than 5 miles, you may be assigned to a shuttle stop location. Some programs (*) provide county-wide transportation, meaning that regardless of your zone, you would receive transportation. For more information please
                contact Charlotte-Mecklenburg School Transportation Services at (980) 343-6715.
            </p>
            <h5>For more information, please visit:</h5>
            <ul class="list-unstyled">
                <li><a href="http://www.cms.k12.nc.us/" target="_blank">Charlotte-Mecklenburg Schools</a></li>
            </ul>
        </div>
    </div>
</template>

<script>
    import jsonToURL from '../modules/jsontourl';
    import format from 'format-number';
    export default {
        name: 'schools',
        data: function() {
            return {
                resultsMagnet: [],
                resultsElementary: [],
                resultsMiddle: [],
                resultsHigh: [],
                tmpTransportationZone: null
            }
        },
        filters: {
            distance: function(dist) {
                return format({
                    'truncate': 1,
                    'suffix': ' miles'
                })(dist / 5280);
            },
            getAsterik: function(id) {
                if ([4429, 8364, 5532, 8482, 7405, 7496, 5520].indexOf(Number(id)) !== -1) {
                    return '*';
                } else {
                    return '';
                }
            }
        },
        watch: {
            '$parent.sharedState.selected.lnglat': 'getResults',
            '$parent.sharedState.show': 'getResults'
        },
        mounted: function() {
            this.getResults();
        },
        methods: {
            apiFetch: function(params, url, setter) {
                let _this = this;
                return fetch(`${url}?${jsonToURL(params)}`)
                    .then(function(response) {
                        return response.json();
                    }).then(function(data) {
                        _this[setter] = data;
                    }).catch(function(ex) {
                        console.log('parsing failed', ex);
                    });
            },
            getResults: function() {
                let _this = this;
                if (_this.$parent.sharedState.selected.lnglat && _this.$parent.sharedState.show.indexOf('schools') !== -1) {
                    // magnet schools
                    _this.apiFetch({
                            'columns': `schl, schlname, address, city, ST_Distance(the_geom,ST_Transform(GeomFromText('POINT( ${Number(_this.$parent.sharedState.selected.lnglat[0])} ${Number(_this.$parent.sharedState.selected.lnglat[1])} )',4326), 2264)) as distance, st_x(st_transform(the_geom, 4326)) as lng, st_y(st_transform(the_geom, 4326)) as lat`,
                            'sort': 'distance'
                        },
                        'https://mcmap.org/api/query/v1/view_schools_magnet',
                        'resultsMagnet'
                    );
                    // elementary school
                    _this.apiFetch({
                            'columns': `name, address, ST_X(ST_Transform(schools.the_geom, 4326)) as lng, ST_Y(ST_Transform(schools.the_geom, 4326)) as lat, ST_Distance(ST_Transform(ST_GeomFromText('POINT(${Number(_this.$parent.sharedState.selected.lnglat[0])} ${Number(_this.$parent.sharedState.selected.lnglat[1])})',4326), 2264), schools.the_geom) as dist`,
                            'limit': 1,
                            'join': `schools;cms_elementary_districts.num = schools.schl`
                        },
                        `https://mcmap.org/api/intersect_point/v1/cms_elementary_districts/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsElementary'
                    );
                    // middle school
                    _this.apiFetch({
                            'columns': `name, address, ST_X(ST_Transform(schools.the_geom, 4326)) as lng, ST_Y(ST_Transform(schools.the_geom, 4326)) as lat, ST_Distance(ST_Transform(ST_GeomFromText('POINT(${Number(_this.$parent.sharedState.selected.lnglat[0])} ${Number(_this.$parent.sharedState.selected.lnglat[1])} )',4326), 2264), schools.the_geom) as dist`,
                            'limit': 1,
                            'join': `schools;cms_middle_districts.num = schools.schl`
                        },
                        `https://mcmap.org/api/intersect_point/v1/cms_middle_districts/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsMiddle'
                    );
                    // high school
                    _this.apiFetch({
                            'columns': `zone, name, address, ST_X(ST_Transform(schools.the_geom, 4326)) as lng, ST_Y(ST_Transform(schools.the_geom, 4326)) as lat, ST_Distance(ST_Transform(ST_GeomFromText('POINT(${Number(_this.$parent.sharedState.selected.lnglat[0])} ${Number(_this.$parent.sharedState.selected.lnglat[1])} )',4326), 2264), schools.the_geom) as dist`,
                            'limit': 1,
                            'join': `schools;cms_high_districts.num = schools.schl`
                        },
                        `https://mcmap.org/api/intersect_point/v1/cms_high_districts/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsHigh'
                    );
                    // temporary for transportation zone
                    _this.apiFetch({
                            'columns': 'choicezn',
                            'limit': 1
                        },
                        `https://mcmap.org/api/intersect_point/v1/tmp_cms_transportation_2017/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'tmpTransportationZone'
                    );
                }
            },
            locationClick: function(rec) {
                this.$parent.sharedState.poi = {
                    'lnglat': [rec.lng, rec.lat],
                    'address': rec.address,
                    'label': rec.name
                };
            }
        }
    }
</script>

<style lang="css">

</style>
