// app/js/components/libraries.vue
<template lang="html">
    <div>
        <div class="mdl-typography--text-center" v-if="results">
            <div class="report-record-highlight">
                <i class="icon icon-library"></i>
                <h2>Your closest library is</h2>
                <h1>{{ results[0].name }}</h1>
                <h3>
                    <a href="javascript:void(0)" v-on:click="locationClick(0)">
                            {{ results[0].address }}, {{ results[0].city}}
                        </a>
                </h3>
                <h4>
                    {{ results[0].distance | distance }}
                </h4>
            </div>
            <table class="mdl-data-table mdl-js-data-table">
                <caption>Libraries Nearby</caption>
                <thead>
                    <tr>
                        <th class="mdl-data-table__cell--non-numeric">Park</th>
                        <th class="mdl-data-table__cell--non-numeric">Address</th>
                        <th class="col-responsive">Distance</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in results">
                        <td class="mdl-data-table__cell--non-numeric">
                            {{ item.name }}
                        </td>
                        <td class="mdl-data-table__cell--non-numeric">
                            <a href="javascript:void(0)" v-on:click="locationClick(index)">
                                    {{ item.address }}, {{item.city}}
                                </a>
                        </td>
                        <td class="nowrap col-responsive">
                            {{ item.distance | distance }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="report-moreinfo mdl-typography--text-left">
            <h5>For more information, please visit:</h5>
            <ul class="list-unstyled">
                <li><a href="http://www.plcmc.org/" target="_blank">Charlotte Mecklenburg Library</a></li>
            </ul>
        </div>
    </div>
</template>

<script>
    import jsonToURL from '../modules/jsontourl';
    import format from 'format-number';
    export default {
        name: 'libraries',
        data: function() {
            return {
                results: null
            }
        },
        filters: {
            distance: function(dist) {
                return format({
                    'truncate': 1,
                    'suffix': ' miles'
                })(dist / 5280);
            }
        },
        watch: {
            '$parent.sharedState.selected.lnglat': 'getResults',
            '$parent.sharedState.show': 'getResults'
        },
        mounted: function() {
            this.getResults();
        },
        methods: {
            getResults: function() {
                let _this = this;
                if (_this.$parent.sharedState.selected.lnglat && _this.$parent.sharedState.show.indexOf('libraries') !== -1) {
                    let params = {
                        'geom_column': 'the_geom',
                        'columns': 'name, address, city, st_x(st_transform(the_geom, 4326)) as lng, st_y(st_transform(the_geom, 4326)) as lat',
                        'limit': '5'
                    };
                    fetch(`https://mcmap.org/api/nearest/v1/libraries/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326?${jsonToURL(params)}`)
                        .then(function(response) {
                            return response.json();
                        }).then(function(data) {
                            _this.results = data;
                        }).catch(function(ex) {
                            console.log('parsing failed', ex);
                        });
                }
            },
            locationClick: function(index) {
                let poi = this.results[index];
                this.$parent.sharedState.poi = {
                    'lnglat': [poi.lng, poi.lat],
                    'address': poi.address,
                    'label': poi.name
                };
            }
        }
    }
</script>

// src/components/Libraries.svelte
<script>
  import { location } from '../store.js'
  import Title from './Title.svelte'
  import Resources from './Resources.svelte'
  import Table from './Table.svelte'
  import Map from './Map.svelte'
  import jsonToURL from '../js/jsonToURL.js'

  // Base table
  const columns = ["Library", "Address", "Distance"]
  const alignRight = [3]
  let rows = []

  // Map
  let showMap = false
  let mapPoints = []

  // Resources
  const resourceLinks = [
    {
      name: 'Charlotte Mecklenburg Library',
      url: 'https://www.cmlibrary.org/'
    },
    {
      name: 'Library data on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=libraries'
    }
  ]

  location.subscribe(value => {
		fetchData()
	})

  function fetchData() {
    // reset variables
    rows = []
    mapPoints = []

    const params = {
      geom_column: "the_geom",
      columns: "name, address, city, st_x(st_transform(the_geom, 4326)) as lng, st_y(st_transform(the_geom, 4326)) as lat",
      limit: "5"
    }

    fetch(`https://api.mcmap.org/v1/nearest/libraries/${$location.lnglat.join(",")},4326?${jsonToURL(params)}`)
      .then(response => response.json())
      .then(data => {
        // make records for table
        data.forEach(el => {
          rows.push([
            el.name,
            `${el.address}, ${el.city}`,
            `${(el.distance / 5280).toFixed(1)} miles`
          ])
          mapPoints.push({
            label: 'L',
            lngLat: [el.lng, el.lat],
            name: el.name,
            address: `${el.address}, ${el.city}`
          })
        })
      })
      .then(() => {
        rows = rows
        mapPoints = mapPoints
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })
  }

  function handleMapOff(event) {
    showMap = false
  }

</script>


<Title title="LIBRARIES" icon="library" />

<Map showMap={showMap} mapPoints={mapPoints} on:mapOff={handleMapOff} />

<Table rows={rows} columns={columns} caption="5 Closest Libraries" alignRight={alignRight} />

<Resources links={resourceLinks} />
