// src/components/property.vue
<template>
    <div>
        <div class="report-record-highlight text-center">
            <svg class="icon icon-property"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-property"></use></svg>
            <h2>Tax Parcel</h2>
            <h1>{{selected.pid}}</h1>
            <h3 v-if="resultsZoning.length > 0">Zoned as {{ resultsZoning[0].zone_class}} {{resultsZoning[0].zone_des}}</h3>
            <Photos :pid="selected.pid"></Photos>
        </div>
        <div v-if="resultsOwnership.length > 0">
            <table>
                <caption>Ownership</caption>
                <thead>
                    <tr>
                        <th>Owner</th>
                        <th>Address</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in resultsOwnership">
                        <td>
                            {{item.first_name}} {{item.last_name}}
                        </td>
                        <td>
                            {{item.address_1}} <br /> {{item.city}}, {{item.state}} {{item.zipcode}}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div v-if="resultsAppraisal.length > 0">
            <table>
                <caption>Tax Appraisal</caption>
                <thead>
                    <tr>
                        <th>Year</th>
                        <th class="text-right">Building</th>
                        <th class="col-responsive text-right">Land</th>
                        <th class="col-responsive text-right">Extra</th>
                        <th class="text-right">Total</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in resultsAppraisal">
                        <td>
                            {{item.tax_year}}
                        </td>
                        <td class="text-right">
                            {{item.building_value | money}}
                        </td>
                        <td class="col-responsive text-right">
                            {{item.land_value | money}}
                        </td>
                        <td class="col-responsive text-right">
                            {{item.extra_features_value | money}}
                        </td>
                        <td class="text-right">
                            {{item.total_value | money}}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div v-if="resultsSales.length > 0">
            <table>
                <caption>Sale History</caption>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th class="text-right">Price</th>
                        <th class="col-responsive">Deed Book</th>
                        <th class="col-responsive">Legal Reference</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in resultsSales">
                        <td>
                            {{item.sale_date}}
                        </td>
                        <td class="text-right">
                            {{ item.sale_price | money }}
                        </td>
                        <td class="col-responsive">
                            {{item.deed_book}}
                        </td>
                        <td class="col-responsive">
                            {{item.legal_reference}}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div v-if="resultsLanduse.length > 0">
            <table>
                <caption>Land Use</caption>
                <thead>
                    <tr>
                        <th>Use</th>
                        <th class="text-right">Units</th>
                        <th class="col-responsive">Neighborhood</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in resultsLanduse">
                        <td>
                            {{item.land_use}}
                        </td>
                        <td class="text-right">
                            {{ item.units | trunc}}
                        </td>
                        <td class="col-responsive">
                            {{item.neighborhood}}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div v-if="resultsBuildings.length > 0">
            <table>
                <caption>Buildings</caption>
                <thead>
                    <tr>
                        <th>Structure</th>
                        <th>Year Built</th>
                        <th class="col-responsive">Exterior</th>
                        <th class="text-right">Area</th>
                        <th class="col-responsive text-right">Beds</th>
                        <th class="col-responsive text-right">Baths</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in resultsBuildings">
                        <td>
                            {{item.property_use_description}}
                        </td>
                        <td>
                            {{item.year_built}}
                        </td>
                        <td class="col-responsive">
                            {{item.exterior_wall_description}}
                        </td>
                        <td class="text-right">
                            {{ item.total_square_feet | sqft }}
                        </td>
                        <td class="col-responsive text-right">
                            {{item.bedrooms}}
                        </td>
                        <td class="col-responsive text-right">
                            {{Number(item.full_baths) + Number(item.three_quarter_baths) + Number(item.half_baths)}}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div v-if="resultsPermits.length > 0">
            <table>
                <caption>Permits</caption>
                <thead>
                    <tr>
                        <th>Year</th>
                        <th>Project</th>
                        <th class="col-responsive text-right">Area</th>
                        <th class="text-right">Cost</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="item in reversePermits">
                        <td>
                            {{item.theyear}}
                        </td>
                        <td>
                            {{item.project_name}}
                        </td>
                        <td class="col-responsive text-right">
                            {{ item.square_footage | sqft }}
                        </td>
                        <td class="text-right">
                            {{ item.construction_cost | money }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="report-moreinfo">
            <h5>For more information, please visit:</h5>
            <ul class="list-unstyled">
                <li><a href="http://polaris.mecklenburgcountync.gov/" target="_blank"  rel="noopener">POLARIS</a></li>
                <li><a href="http://charmeck.org/mecklenburg/county/AssessorsOffice/Pages/Home.aspx" target="_blank"  rel="noopener">County Assessor's Office</a></li>
                <li><a href="http://charmeck.org/city/charlotte/planning/Pages/Home.aspx" target="_blank"  rel="noopener">Charlotte-Mecklenburg Planning</a></li>
            </ul>
        </div>
    </div>
</template>

<script>
import jsonToURL from "../js/jsontourl";
import format from "format-number";
import Photos from "./photos.vue";

export default {
  name: "property",

  components: {
    Photos: Photos
  },

  data: function() {
    return {
      resultsZoning: [],
      resultsOwnership: [],
      resultsAppraisal: [],
      resultsSales: [],
      resultsLanduse: [],
      resultsBuildings: [],
      resultsPermits: []
    };
  },

  computed: {
    reversePermits() {
      return this.resultsPermits.slice().reverse();
    },
    selected () {
      return this.$store.getters.selected
    },
    show () {
      return this.$store.getters.show
    }
  },

  watch: {
    selected: "getResults",
    show: "getResults"
  },

  filters: {
    money: function(num) {
      return format({
        prefix: "$",
        truncate: 0
      })(num);
    },
    trunc: function(num) {
      return format({
        truncate: 0
      })(num);
    },
    sqft: function(num) {
      return format({
        truncate: 0,
        suffix: " Sq. Ft."
      })(num);
    },
    reverse: function(value) {
      return value.slice().reverse();
    }
  },

  mounted: function() {
    this.getResults();
  },

  methods: {
    apiFetch: function(params, url, setter) {
      let _this = this;
      return fetch(`${url}?${jsonToURL(params)}`)
        .then(function(response) {
          return response.json();
        })
        .then(function(data) {
          _this[setter] = data;
        })
        .catch(function(ex) {
          console.log("parsing failed", ex);
        });
    },
    getResults: function() {
      let _this = this;
      if (
        _this.selected.pid &&
        _this.show.indexOf("property") !== -1
      ) {
        // zoning
        _this.apiFetch(
          {
            columns: "zone_des, zone_class",
            filter: "zone_des <> 'sm_towns'",
            geom_column: "the_geom"
          },
          `https://mcmap.org/api/intersect_point/v1/view_zoning/${_this.selected.lnglat.join(
            ","
          )}/4326`,
          "resultsZoning"
        );
        // ownership
        _this.apiFetch(
          {
            pid: _this.selected.pid
          },
          "https://mcmap.org/rest/v3/ws_cama_ownership.php",
          "resultsOwnership"
        );
        // appraisal
        _this.apiFetch(
          {
            pid: _this.selected.pid
          },
          "https://mcmap.org/rest/v3/ws_cama_appraisal.php",
          "resultsAppraisal"
        );
        // sales history
        _this.apiFetch(
          {
            pid: _this.selected.pid
          },
          "https://mcmap.org/rest/v3/ws_cama_saleshistory.php",
          "resultsSales"
        );
        // land use
        _this.apiFetch(
          {
            pid: _this.selected.pid
          },
          "https://mcmap.org/rest/v3/ws_cama_landuse.php",
          "resultsLanduse"
        );
        // building information
        _this.apiFetch(
          {
            pid: _this.selected.pid
          },
          "https://mcmap.org/rest/v3/ws_cama_building.php",
          "resultsBuildings"
        );
        // building permits
        _this.apiFetch(
          {
            columns:
              "extract(year from t.date_completed_co_process) as theyear, t.project_name,t.square_footage,t.construction_cost",
            filter: `f.pid = '${
              _this.selected.pid
            }' and t.job_status = 'COMPL'`,
            sort: "t.date_completed_co_process",
            limit: 100,
            geom_column_from: "the_geom",
            geom_column_to: "the_geom"
          },
          "https://mcmap.org/api/intersect_feature/v1/tax_parcels/building_permits",
          "resultsPermits"
        );
      }
    }
  }
};
</script>

// src/components/Property.svelte
<script>
  import { location } from '../store.js'
  import Title from './Title.svelte'
  import Resources from './Resources.svelte'
  import Table from './Table.svelte'
  import Map from './Map.svelte'
  import RecordHighlight from './RecordHighlight.svelte'
  import jsonToURL from '../js/jsonToURL.js'
  import { formatCommas, formatMoney, formatDate } from '../js/formatNumbers.js'
  import toastMaker from '../js/toastMaker'

  // Tables
  const ownerTable = {
    caption: "Ownership",
    columns: ["Owner", "Address"],
    rows: []
  }
  const appraisalTable = {
    caption: "Tax Appraisal",
    columns: ["Year", "Building", "Land", "Extra", "Total"],
    alignRight: [2,3,4,5],
    rows: []
  }
  const saleTable = {
    caption: "Sale History",
    columns: ["Date", "Deed Book", "Legal Reference", "Price"],
    alignRight: [2, 3, 4],
    rows: []
  }
  const useTable = {
    caption: "Land Use",
    columns: ["Use", "Units", "Neighborhood"],
    alignRight: [2],
    rows: []
  }
  const buildingTable = {
    caption: "Buildings",
    columns: ["Structure", "Year Built", "Exterior", "Area", "Beds", "Baths"],
    alignRight: [4,5,6],
    rows: []
  }
  const permitTable = {
    caption: "Building Permits",
    columns: ["Date", "Project", "Area", "Cost"],
    alignRight: [3,4],
    rows: []
  }

  // other variables
  let zoning = null
  let photo= null

  // Map
  let showMap = false

  // Resources
  const resourceLinks = [
    {
      name: 'POLARIS',
      url: 'http://polaris.mecklenburgcountync.gov/'
    },
    {
      name: "County Assessor's Office",
      url: 'https://www.mecknc.gov/assessorsoffice/Pages/Home.aspx'
    },
    {
      name: 'Office of the Tax Collector',
      url: 'https://www.mecknc.gov/taxcollections/Pages/Home.aspx'
    },
    {
      name: 'Charlotte Planning',
      url: 'https://charlottenc.gov/planning/Pages/Home.aspx'
    },
    {
      name: 'Tax data on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=tax'
    }
  ]

  location.subscribe(value => {
		fetchData()
	})

  function fetchData() {
    // reset variables
    zoning = null;
    photo = null;
    [ownerTable, appraisalTable, saleTable, useTable, buildingTable, permitTable].forEach(item => {
      item.rows = []
    })


    // house photo
    fetch(`https://api.mcmap.org/v1/query/property_photos?${jsonToURL({
      columns: 'image_path,image_date',
      filter: `taxpid = '${$location.pid}'`,
      sort: 'image_date desc'
    })}`)
      .then(response => response.json())
      .then(data => {
        data.length > 0 ?
        photo = `<a href=${data[0].image_path} class="block mt-2" target="_blank">
            <img src=${data[0].image_path} class="max-w-full shadow-xl rounded-lg" alt="property photo">
          </a>`
        : photo = null
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })

    // zoning
    fetch(`https://api.mcmap.org/v1/intersect_point/view_zoning/${$location.lnglat.join(',')},4326?${jsonToURL({
      columns: 'zone_des,zone_class',
      geom_column: "the_geom"
    })}`)
      .then(response => response.json())
      .then(data => {
        data.length > 0 ?
          zoning = `Zoned as <span class="font-bold">${data[0].zone_class} ${data[0].zone_des}</span>` : zoning = null
      })
      .catch(ex => {
        console.log("parsing failed", ex);
      })

    // ownership
    fetch(`https://api.mcmap.org/v1/query/cama_tb_pubowner?${jsonToURL({
      columns: 'nme_ownerlastname,nme_ownerfirstname,txt_mailaddr1,txt_mailaddr2,txt_city,txt_state,txt_zipcode',
      filter: `id_pid = '${$location.pid}'`
    })}`)
      .then(response => response.json())
      .then(data => {
        data.forEach(el => {
          ownerTable.rows.push([
            `${el.nme_ownerfirstname} ${el.nme_ownerlastname}`,
            `${el.txt_mailaddr1} ${el.txt_mailaddr2 || ''}<br>${el.txt_city}, ${el.txt_state} ${el.txt_zipcode}`
          ])
        })
      })
      .then(() => {
        ownerTable.rows = ownerTable.rows
      })
      .catch(ex => {
        toastMaker( "error", "We're having a problem loading this data. Please try back later.")
        console.log("parsing failed", ex);
      })

    // appraisal
    fetch(`https://api.mcmap.org/v1/query/cama_tb_pubparcelinfo?${jsonToURL({
      columns: 'txt_taxyear,amt_netbldgvalue,amt_extrafeaturevalue,amt_landvalue,amt_totalvalue',
      filter: `id_pid = '${$location.pid}'`
    })}`)
      .then(response => response.json())
      .then(data => {
        data.forEach(el => {
          appraisalTable.rows.push([
            el.txt_taxyear,
            formatMoney(el.amt_netbldgvalue),
            formatMoney(el.amt_landvalue),
            formatMoney(el.amt_extrafeaturevalue),
            formatMoney(el.amt_totalvalue)
          ])
        })
      })
      .then(() => {
        appraisalTable.rows = appraisalTable.rows
      })
      .catch(ex => {
        toastMaker( "error", "We're having a problem loading this data. Please try back later.")
        console.log("parsing failed", ex);
      })

    // sale history
    fetch(`https://api.mcmap.org/v1/query/cama_tb_pubsales?${jsonToURL({
      columns: 'dte_dateofsale,amt_price,txt_deedbook,txt_deedpage,txt_legalreference',
      filter: `id_pid = '${$location.pid}'`
    })}`)
      .then(response => response.json())
      .then(data => {
        data.forEach(el => {
          saleTable.rows.push([
            formatDate(el.dte_dateofsale),
            `${el.txt_deedbook} ${el.txt_deedpage}`,
            el.txt_legalreference,
            formatMoney(el.amt_price),
          ])
        })
      })
      .then(() => {
        saleTable.rows = saleTable.rows
      })
      .catch(ex => {
        toastMaker( "error", "We're having a problem loading this data. Please try back later.")
        console.log("parsing failed", ex);
      })

    // land use
    fetch(`https://api.mcmap.org/v1/query/cama_tb_publand,cama_ctb_publanduse?${jsonToURL({
      columns: 'txt_landUse_fulldesc,cnt_landunits,txt_neigh_desc',
      filter: `cama_tb_publand.cde_landusecode = cama_ctb_publanduse.cde_landuse and id_pid = '${$location.pid}'`
    })}`)
      .then(response => response.json())
      .then(data => {
        data.forEach(el => {
          useTable.rows.push([
            el.txt_landuse_fulldesc,
            formatCommas(el.cnt_landunits),
            el.txt_neigh_desc || ''
          ])
        })
      })
      .then(() => {
        useTable.rows = useTable.rows
      })
      .catch(ex => {
        toastMaker( "error", "We're having a problem loading this data. Please try back later.")
        console.log("parsing failed", ex);
      })

    // buildings
    fetch(`https://api.mcmap.org/v1/query/cama_tb_pubbuilding?${jsonToURL({
      columns: 'txt_propertyuse_desc,num_yearbuilt,txt_extwall_desc,num_grossarea,num_bedrooms,cnt_fullbaths,cnt_threeqtrbaths,cnt_halfbaths',
      filter: `id_pid = '${$location.pid}'`
    })}`)
      .then(response => response.json())
      .then(data => {
        data.forEach(el => {
          buildingTable.rows.push([
            el.txt_propertyuse_desc,
            el.num_yearbuilt,
            el.txt_extwall_desc,
            formatCommas(el.num_grossarea) + ' Sq. Ft.',
            el.num_bedrooms,
            el.cnt_fullbaths + el.cnt_threeqtrbaths + el.cnt_halfbaths
          ])
        })
      })
      .then(() => {
        buildingTable.rows = buildingTable.rows
      })
      .catch(ex => {
        toastMaker( "error", "We're having a problem loading this data. Please try back later.")
        console.log("parsing failed", ex);
      })

    // building permits
    fetch(`https://api.mcmap.org/v1/intersect_feature/tax_parcels/building_permits?${jsonToURL({
      columns: 'date_completed_co_process,project_name,square_footage,construction_cost',
      filter: `tax_parcels.pid = '${$location.pid}'`,
      geom_column_from: "the_geom",
      geom_column_to: "the_geom"
    })}`)
      .then(response => response.json())
      .then(data => {
        data.forEach(el => {
          permitTable.rows.push([
            formatDate(el.date_completed_co_process),
            el.project_name,
            formatCommas(el.square_footage) + ' Sq. Ft.',
            formatMoney(el.construction_cost)
          ])
        })
      })
      .then(() => {
        permitTable.rows = permitTable.rows
      })
      .catch(ex => {
        toastMaker( "error", "We're having a problem loading this data. Please try back later.")
        console.log("parsing failed", ex);
      })

  }

</script>

<Title title="PROPERTY" icon="property" />

<Map showMap={showMap} />

<div class="flex flex-row flex-wrap justify-around">
  <RecordHighlight top="Parcel ID" sub={zoning} headline={$location.pid} detail={photo} />
</div>

<Table {...ownerTable} />
<Table {...appraisalTable} />
<Table {...saleTable} />
<Table {...useTable} />
<Table {...buildingTable} />
<Table {...permitTable} />

<Resources links={resourceLinks} />
