// app/js/components/voting.vue
<template lang="html">
    <div>
        <div class="mdl-typography--text-center">
            <div class="report-record-highlight" v-if="resultsPrecinct.length > 0">
                <i class="icon icon-voting"></i>
                <h2>Your Polling Location is</h2>
                <h1>{{resultsPrecinct[0].label}}</h1>
                <h3><a href="javascript:void(0)" v-on:click="locationClick(resultsPrecinct[0])">
                            {{resultsPrecinct[0].address}}</a></h3>
                <h4>Precinct {{resultsPrecinct[0].precinct}}</h4>
            </div>
        </div>
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsOfficials.length > 0">
                    <i class="icon icon-person"></i>
                    <h2>Your US SENATE representatives are</h2>
                    <h1 v-for="(item, index) in getSenate(resultsOfficials, 'national_senate')">
                        {{item.representative}}
                    </h1>
                </div>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsOfficials.length > 0 && resultsNatlcong.length > 0">
                    <i class="icon icon-person"></i>
                    <h2>Your US CONGRESSIONAL DISTRICT representative is</h2>
                    <h1>{{resultsNatlcong[0].district | repFilter(resultsOfficials, 'national_congressional')}}</h1>
                    <h3>District {{resultsNatlcong[0].district}}</h3>
                </div>
            </div>
        </div>
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsOfficials.length > 0 && resultsNCSenate.length > 0">
                    <i class="icon icon-person"></i>
                    <h2>Your NC SENATE DISTRICT representative is</h2>
                    <h1>{{resultsNCSenate[0].district | repFilter(resultsOfficials, 'state_senate')}}</h1>
                    <h3>District {{resultsNCSenate[0].district}}</h3>
                </div>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsOfficials.length > 0 && resultsNCHouse.length > 0">
                    <i class="icon icon-person"></i>
                    <h2>Your NC HOUSE DISTRICT representative is</h2>
                    <h1>{{resultsNCHouse[0].district | repFilter(resultsOfficials, 'state_house')}}</h1>
                    <h3>District {{resultsNCHouse[0].district}}</h3>
                </div>
            </div>
        </div>
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsOfficials.length > 0 && resultsPrecinct.length > 0">
                    <i class="icon icon-person"></i>
                    <h2>Your COUNTY COMMISSION DISTRICT representative is</h2>
                    <h1>{{resultsPrecinct[0].cc | repFilter(resultsOfficials, 'county_commission')}}</h1>
                    <h3>District {{resultsPrecinct[0].cc}}</h3>
                    <h4>
                        At large: {{ getAtLarge(resultsOfficials, 'county_commission') }}
                    </h4>
                </div>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-cell--12-col-tablet mdl-typography--text-center">
                <div class="report-record-highlight" v-if="resultsOfficials.length > 0 && resultsPrecinct.length > 0">
                    <i class="icon icon-person"></i>
                    <h2>Your SCHOOL BOARD DISTRICT representative is</h2>
                    <h1>{{resultsPrecinct[0].school | repFilter(resultsOfficials, 'board_of_education')}}</h1>
                    <h3>District {{resultsPrecinct[0].school}}</h3>
                    <h4>
                        At large: {{ getAtLarge(resultsOfficials, 'board_of_education') }}
                    </h4>
                </div>
            </div>
        </div>
        <div class="mdl-typography--text-center">
            <div class="report-record-highlight" v-if="resultsOfficials.length > 0 && resultsCharlotte.length > 0">
                <i class="icon icon-person"></i>
                <h2>Your CHARLOTTE CITY COUNCIL DISTRICT representative is</h2>
                <h1>{{resultsCharlotte[0].district | repFilter(resultsOfficials, 'charlotte_city_council')}}</h1>
                <h3>District {{resultsCharlotte[0].district}}</h3>
                <h4>
                    At large: {{ getAtLarge(resultsOfficials, 'charlotte_city_council') }}
                </h4>
            </div>
        </div>
        <div class="report-moreinfo mdl-typography--text-left">
            <h5>For more information, please visit:</h5>
            <ul class="list-unstyled">
                <li><a href="http://www.meckboe.org/" target="_blank">Mecklenburg County Board of Elections</a></li>
            </ul>
        </div>
    </div>
</template>

<script>
    import jsonToURL from '../modules/jsontourl';
    import format from 'format-number';
    export default {
        name: 'voting',
        data: function() {
            return {
                resultsOfficials: [],
                resultsPrecinct: [],
                resultsNatlcong: [],
                resultsNCSenate: [],
                resultsNCHouse: [],
                resultsCharlotte: []
            }
        },
        filters: {
            distance: function(dist) {
                return format({
                    'truncate': 1,
                    'suffix': ' miles'
                })(dist / 5280);
            },
            repFilter: function(id, recs, filt) {
                let rep = recs.filter(function(r) {
                    return r.district_type === filt && r.district == id;
                });
                return rep[0].representative;
            }
        },
        watch: {
            '$parent.sharedState.selected.lnglat': 'getResults',
            '$parent.sharedState.show': 'getResults'
        },
        mounted: function() {
            this.getOfficials();
            this.getResults();
        },
        methods: {
            apiFetch: function(params, url, setter) {
                let _this = this;
                return fetch(`${url}?${jsonToURL(params)}`)
                    .then(function(response) {
                        return response.json();
                    }).then(function(data) {
                        _this[setter] = data;
                    }).catch(function(ex) {
                        console.log('parsing failed', ex);
                    });
            },
            getOfficials: function() {
                let _this = this;
                _this.apiFetch({
                        'sort': 'district'
                    },
                    'https://mcmap.org/api/query/v1/elected_officials',
                    'resultsOfficials'
                );
            },
            getResults: function() {
                let _this = this;
                if (_this.$parent.sharedState.selected.lnglat && _this.$parent.sharedState.show.indexOf('voting') !== -1) {
                    // voting precincts
                    _this.apiFetch({
                            'geom_column': 'the_geom',
                            'limit': 1,
                            'columns': `voting_precincts.cc, voting_precincts.school, polling_locations.name as label,polling_locations.address,voting_precincts.precno as precinct,st_x(st_transform(polling_locations.the_geom, 4326)) as lng, st_y(st_transform(polling_locations.the_geom, 4326)) as lat, ST_Distance(polling_locations.the_geom,ST_Transform(GeomFromText('POINT(${Number(_this.$parent.sharedState.selected.lnglat[0])} ${Number(_this.$parent.sharedState.selected.lnglat[1])})',4326), 2264)) as distance`,
                            'join': 'polling_locations;voting_precincts.precno = polling_locations.precno'
                        },
                        `https://mcmap.org/api/intersect_point/v1/voting_precincts/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsPrecinct'
                    );
                    // national congressional
                    _this.apiFetch({
                            'geom_column': 'the_geom',
                            'columns': `district as district`
                        },
                        `https://mcmap.org/api/intersect_point/v1/national_congressional/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsNatlcong'
                    );
                    // state senate
                    _this.apiFetch({
                            'geom_column': 'the_geom',
                            'columns': 'senate as district'
                        },
                        `https://mcmap.org/api/intersect_point/v1/state_senate/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsNCSenate'
                    );
                    // state house
                    _this.apiFetch({
                            'geom_column': 'the_geom',
                            'columns': 'house as district'
                        },
                        `https://mcmap.org/api/intersect_point/v1/state_house/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsNCHouse'
                    );
                    // charlotte city council
                    _this.apiFetch({
                            'geom_column': 'the_geom',
                            'columns': 'citydist as district'
                        },
                        `https://mcmap.org/api/intersect_point/v1/city_council/${_this.$parent.sharedState.selected.lnglat.join(',')}/4326`,
                        'resultsCharlotte'
                    );
                }
            },
            locationClick: function(rec) {
                this.$parent.sharedState.poi = {
                    'lnglat': [rec.lng, rec.lat],
                    'address': rec.address,
                    'label': rec.name
                };
            },
            getSenate: function(recs, filt) {
                return recs.filter(function(r) {
                    return r.district_type === filt;
                });
            },
            getAtLarge: function(recs, filt) {
                recs = recs.filter(function(r) {
                    return r.district_type === filt && r.district === 'At-Large';
                });
                return recs.map(function(item) {
                    return item.representative;
                }).join(', ')
            }
        }
    }
</script>

<style lang="css">

</style>

// src/components/Voting.svelte
<script>
  import { location } from '../store.js'
  import Title from './Title.svelte'
  import Resources from './Resources.svelte'
  import Map from './Map.svelte'
  import Representative from './Representative.svelte'
  import RecordHighlight from './RecordHighlight.svelte'
  import jsonToURL from '../js/jsonToURL.js'

  // Map
  let showMap = false

  // Resources
  const resourceLinks = [
    {
      name: 'Mecklenburg County Board of Elections',
      url: 'https://www.mecknc.gov/BOE/Pages/default.aspx'
    },
    {
      name: 'Voting Precincts and Polling Locations on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=vot'
    },
    {
      name: 'Districts on Open Mapping',
      url: 'http://maps.co.mecklenburg.nc.us/openmapping/data.html?search=districts'
    }
  ]

  // Local data catchers
  let officials = null
  let nationalHouse = []
  let stateSenate = []
  let stateHouse = []
  let countyCommission = []
  let countyBoard = []
  let local = []
  let pollingLocation = {
    headline: null,
    sub: null,
    detail: null
  }
  let mapPoints = []

  location.subscribe(value => {
    Promise.all([
      fetch('https://api.mcmap.org/v1/query/boe_elected_officials?sort=branch,district').then(resp => resp.json()),
      fetch(`https://api.mcmap.org/v1/intersect_point/view_political_districts/${$location.lnglat[0]},${$location.lnglat[1]},4326?columns=districttype,district`).then(resp => resp.json())
    ])
    .then(data => {
      officials = data[0]

      // national house
      nationalHouse = officials.filter(el => el.branch.indexOf('US House of Representatives') !== -1 &&
        el.district === data[1].filter(el => el.districttype === 'national_congressional')[0].district)
      // county commsion
      countyCommission = officials.filter(el => el.branch.indexOf('Board of Commissioners') !== -1 &&
        (el.district === data[1].filter(el => el.districttype === 'county_commission')[0].district || el.district === 'At-Large'))
      // school board
      countyBoard = officials.filter(el => el.branch.indexOf('Board of Education') !== -1 &&
        (el.district === data[1].filter(el => el.districttype === 'school_board')[0].district || el.district === 'At-Large'))
      // state senate
      stateSenate = officials.filter(el => el.branch.indexOf('NC State Senate') !== -1 &&
          el.district === data[1].filter(el => el.districttype === 'state_senate')[0].district)
      // state house
      stateHouse = officials.filter(el => el.branch.indexOf('NC House of Representatives') !== -1 &&
          el.district === data[1].filter(el => el.districttype === 'state_house')[0].district)
      // local
      if (data[1].filter(el => el.districttype === 'charlotte_city_council').length > 0) {
        // charlotte
        local = officials.filter(el => el.branch.indexOf('Charlotte') !== -1 &&
          (el.district === data[1].filter(el => el.districttype === 'charlotte_city_council')[0].district || el.district === 'At-Large'))
      } else if (data[1].filter(el => el.districttype === 'jurisdictions' && el.district != 'Stallings' && el.district != 'Mecklenburg').length > 0) {
        // towns
        local = officials.filter(el => el.branch.indexOf(data[1].filter(el => el.districttype === 'jurisdictions')[0].district) !== -1)
      }

      fetchPollingLocation(data[1].filter(el => el.districttype === 'voting_precincts')[0].district)

    })

  })

  function fetchPollingLocation(precno) {
    const params = {
      geom_column: "voting_precincts.the_geom",
      columns: `name,
        address,
        precno,
        st_x(st_transform(the_geom, 4326)) as lng,
        st_y(st_transform(the_geom, 4326)) as lat,
        ST_Distance(the_geom,ST_Transform(GeomFromText('POINT(${$location.lnglat[0]} ${$location.lnglat[1]})',4326), 2264)) as distance
        `,
      filter: `precno = ${precno}`
    }
    fetch(`https://api.mcmap.org/v1/query/polling_locations?` + jsonToURL(params))
      .then(response => response.json())
      .then(json => {
        pollingLocation.headline = json[0].name
        pollingLocation.sub = json[0].address
        pollingLocation.detail = `Precinct ${json[0].precno}`
        mapPoints = [{
          label: 'V',
          lngLat: [json[0].lng, json[0].lat],
          name: json[0].name,
          address: `${json[0].address}`
        }]
      })
  }


</script>

<style>
.voting-h2 {
  @apply text-center w-full text-3xl tracking-widest text-gray-600 dark:text-gray-400 pt-12 uppercase font-bold;
}
</style>


<Title title="VOTING" icon="voting" />

<Map showMap={showMap} mapPoints={mapPoints} />

<!-- Polling Location -->

<div class="flex flex-row flex-wrap justify-around print:block">
  <RecordHighlight
    top="Your Polling Location is"
    headline={pollingLocation.headline}
    sub={pollingLocation.sub}
    detail={pollingLocation.detail}
  />
</div>

{#if officials}

<!-- National -->
<div class="flex flex-row flex-wrap justify-around print:block">
  <h2 class="voting-h2">National</h2>
  <Representative reps={officials.filter(el => el.branch === 'President of the United States')} />
  <Representative reps={officials.filter(el => el.branch === 'Vice President of the United States')} />
  <Representative reps={officials.filter(el => el.branch === 'US Senate')} />
  <Representative reps={nationalHouse} />
</div>

<!-- State -->
<div class="flex flex-row flex-wrap justify-around print:block">
  <h2 class="voting-h2">State</h2>
  <Representative reps={officials.filter(el => el.branch.indexOf('Governor') !== -1)} />
  <Representative reps={stateSenate} />
  <Representative reps={stateHouse} />
</div>

<!-- County -->
<div class="flex flex-row flex-wrap justify-around print:block">
  <h2 class="voting-h2">County</h2>
  <Representative reps={countyCommission} />
  <Representative reps={countyBoard} />
</div>

<!-- Local -->
<div class="flex flex-row flex-wrap justify-around print:block">
  <h2 class="voting-h2">Local</h2>
  <Representative reps={local} />
</div>

{/if}

<Resources links={resourceLinks} />
